use fputs() instead of fprintf() for fixed strings
This fixes

  error: format not a string literal and no format arguments

when compiling with -Werror=format-security.